[package]

name = "websocket"
version = "0.13.0"
authors = ["cyderize <admin@cyderize.org>"]

description = "A WebSocket (RFC6455) library for Rust."

documentation = "http://cyderize.github.io/rust-websocket/doc/websocket/"
homepage = "http://cyderize.github.io/rust-websocket/"
repository = "https://github.com/cyderize/rust-websocket.git"

readme = "README.md"

keywords = ["websocket", "websockets", "rfc6455"]

license = "MIT"

[dependencies]
hyper = "*"
unicase = "*"
openssl = "*"
url = "*"
rustc-serialize = "*"
bitflags = "*"
rand = "*"
byteorder = "*"

[features]
nightly = ["hyper/nightly"]
